spring:
  application:
    name: urbot-client
  security:
    user:
      name: test
      password: 123456
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  